server:
  port: 80


spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      routes:
        - id: java-demo
          uri: http://localhost:8080
          predicates:
            - Path=/java-demo/**
          filters:
            - RewritePath=/java-demo/?(?<segment>.*), /$\{segment}
            - name: AuthFilter
              args:
                baseMessage: SCG AuthFilter
                preLogger: true
                postLogger: true

management:
  endpoint:
    gateway:
      enabled:
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.r2dbc: DEBUG