### post member
POST http://localhost/java-demo/api/v1/member
token: A.B.C
Content-Type: application/json
{
    "name": "테스트",
    "email" :"test.kaka@gmail.com"
}

### get member list
GET http://localhost/java-demo/api/v1/member
token: Bearer {token}

### get jwt token
POST http://localhost/auth/token
